<?php

namespace App\Http\Controllers\Admin;

use App\Models\Image;
use FilesystemIterator;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

class ImageController extends Controller
{
    public function picker(Request $request)
    {
        $perPage = 18;

        if ($request->filled('search')) {
            return $this->pickerSearch($request, $perPage);
        }

        $query = Image::query()->orderBy('created_at', 'desc');
        $images = $query->paginate($perPage)->withQueryString();

        return response()->json([
            'images' => $images->map(function ($image) {
                return $this->pickerPayload($image);
            }),
            'last_page' => $images->lastPage(),
            'current_page' => $images->currentPage(),
            'total' => $images->total(),
        ]);
    }

    /**
     * Search across the images table AND the uploads folder on disk so that
     * every image (even ones without an images table row) is findable.
     */
    private function pickerSearch(Request $request, int $perPage)
    {
        $term = trim((string) $request->search);
        if ($term === '') {
            return $this->picker($request->merge(['search' => null]));
        }

        $entries = []; // keyed by normalized relative path to de-duplicate
        $seenBases = []; // basename -> true, to collapse folder-duplicate copies (2026/07 vs 2026/08)

        // Auto-generated responsive variants (e.g. _250.webp, _500.webp) are
        // regenerated by the site on demand — they are not meant to be picked.
        $isVariant = function (string $name): bool {
            return (bool) preg_match('/_(\d{3})\.webp$/i', $name)
                || (bool) preg_match('/_(main|thumb)\.webp$/i', $name);
        };

        $add = function ($path, $originalName, $filename, ?Image $image = null) use (&$entries, &$seenBases, $isVariant) {
            $key = Image::normalizePath($path) ?? $path;
            if ($key === null || $key === '' || isset($entries[$key])) {
                return;
            }
            if ($isVariant($filename)) {
                return;
            }
            $baseName = pathinfo($filename, PATHINFO_FILENAME);
            if (isset($seenBases[$baseName])) {
                return; // already showing a copy of this image
            }
            $seenBases[$baseName] = true;

            $filePath = null;
            if (! $image) {
                $full = resolveImageSource('storage/'.ltrim($key, '/'));
                if ($full) {
                    $filePath = $full;
                }
            }

            $mime = $image?->mime_type
                ?? (($filePath && is_callable('mime_content_type')) ? (mime_content_type($filePath) ?: 'image/jpeg') : 'image/jpeg');
            $size = $image?->size ?? ($filePath ? filesize($filePath) : 0);

            $entries[$key] = [
                'id' => $image?->id ?? (1010000 + crc32($key)),
                'thumb_url' => str_starts_with($key, 'assets/')
                    ? asset($key)
                    : asset('storage/'.ltrim($key, '/')),
                'original_name' => $originalName,
                'filename' => $filename,
                'path' => $key,
                'mime_type' => $mime,
                'size_in_kb' => $size ? round($size / 1024, 1).' KB' : '-',
            ];
        };

        // 1) Database matches (original_name, alt_text, title, filename)
        Image::where(function ($q) use ($term) {
            $q->where('original_name', 'like', "%{$term}%")
                ->orWhere('alt_text', 'like', "%{$term}%")
                ->orWhere('title', 'like', "%{$term}%")
                ->orWhere('filename', 'like', "%{$term}%");
        })
            ->orderBy('created_at', 'desc')
            ->take(600)
            ->get()
            ->each(function (Image $image) use ($add) {
                $add($image->path, $image->original_name, $image->filename, $image);
            });

        // 2) Filesystem matches under uploads/ (files without a DB row)
        $base = storage_path('app/public/uploads');
        if (is_dir($base)) {
            $extensions = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
            $fsMatches = 0;
            $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($base, FilesystemIterator::SKIP_DOTS));
            foreach ($iterator as $file) {
                if (! $file->isFile()) {
                    continue;
                }
                $name = $file->getFilename();
                $ext = strtolower($file->getExtension());
                if (! in_array($ext, $extensions, true) || stripos($name, $term) === false) {
                    continue;
                }
                $rel = 'uploads/'.ltrim(str_replace($base.'/', '', $file->getPathname()), '/');
                $add($rel, $name, $name);
                if (++$fsMatches >= 600) {
                    break;
                }
            }
        }

        $items = array_values($entries);
        $total = count($items);
        $page = max(1, (int) $request->input('page', 1));
        $slice = array_slice($items, ($page - 1) * $perPage, $perPage);
        $paginator = new LengthAwarePaginator($slice, $total, $perPage, $page);

        return response()->json([
            'images' => $slice,
            'last_page' => $paginator->lastPage(),
            'current_page' => $paginator->currentPage(),
            'total' => $total,
        ]);
    }

    private function pickerPayload(Image $image): array
    {
        return [
            'id' => $image->id,
            'thumb_url' => $image->thumb_url,
            'original_name' => $image->original_name,
            'filename' => $image->filename,
            'path' => $image->path,
            'mime_type' => $image->mime_type,
            'size_in_kb' => $image->size_in_kb,
        ];
    }

    public function pickerStore(Request $request)
    {
        $request->validate([
            'images' => 'required|array|max:10',
            'images.*' => 'required|image|mimes:jpeg,png,jpg,gif,webp|max:20480',
        ]);

        $uploaded = [];
        foreach ($request->file('images') as $file) {
            $image = Image::storeFromUpload($file, 'images');
            $uploaded[] = [
                'id' => $image->id,
                'thumb_url' => $image->thumb_url,
                'original_name' => $image->original_name,
                'filename' => $image->filename,
                'path' => $image->path,
                'mime_type' => $image->mime_type,
                'size_in_kb' => $image->size_in_kb,
            ];
        }

        return response()->json(['success' => true, 'images' => $uploaded]);
    }

    public function pickerStoreFromUrl(Request $request)
    {
        $request->validate([
            'url' => 'required|url|max:2048',
        ]);

        $url = $request->url;

        if (! preg_match('/^https?:\/\//i', $url)) {
            return response()->json(['success' => false, 'message' => 'Only http/https image URLs are allowed.'], 422);
        }

        $context = stream_context_create([
            'http' => [
                'timeout' => 20,
                'ignore_errors' => true,
                'user_agent' => 'Mozilla/5.0 (compatible; StAutopartsImageDownloader/1.0)',
            ],
            'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
        ]);

        $contents = @file_get_contents($url, false, $context);
        if ($contents === false || strlen($contents) === 0) {
            return response()->json(['success' => false, 'message' => 'Could not download the image from the provided URL.'], 422);
        }

        if (strlen($contents) > 10 * 1024 * 1024) {
            return response()->json(['success' => false, 'message' => 'The image is larger than the 10MB limit.'], 422);
        }

        $info = @getimagesizefromstring($contents);
        if ($info === false) {
            return response()->json(['success' => false, 'message' => 'The URL does not point to a valid image.'], 422);
        }

        $allowedMimes = [
            'image/jpeg' => 'jpg',
            'image/png' => 'png',
            'image/gif' => 'gif',
            'image/webp' => 'webp',
            'image/svg+xml' => 'svg',
        ];

        $mime = $info['mime'];
        if (! isset($allowedMimes[$mime])) {
            return response()->json(['success' => false, 'message' => 'Unsupported image type: '.$mime], 422);
        }
        $ext = $allowedMimes[$mime];

        $originalName = basename((string) parse_url($url, PHP_URL_PATH)) ?: ('image.'.$ext);
        if (! preg_match('/\.'.preg_quote($ext, '/').'$/i', $originalName)) {
            $originalName = pathinfo($originalName, PATHINFO_FILENAME).'.'.$ext;
        }

        $tmp = tempnam(sys_get_temp_dir(), 'imgdl_');
        if ($tmp === false) {
            return response()->json(['success' => false, 'message' => 'Could not create a temporary file.'], 500);
        }

        try {
            file_put_contents($tmp, $contents);
            $uploadedFile = new UploadedFile($tmp, $originalName, $mime, null, true);
            $image = Image::storeFromUpload($uploadedFile, 'images');
        } finally {
            @unlink($tmp);
        }

        return response()->json([
            'success' => true,
            'image' => [
                'id' => $image->id,
                'thumb_url' => $image->thumb_url,
                'original_name' => $image->original_name,
                'filename' => $image->filename,
                'path' => $image->path,
                'mime_type' => $image->mime_type,
                'size_in_kb' => $image->size_in_kb,
            ],
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'images' => 'required|array',
            'images.*' => 'required|image|mimes:jpeg,png,jpg,gif,webp|max:20480',
        ]);

        $uploaded = 0;
        foreach ($request->file('images') as $file) {
            Image::storeFromUpload($file, 'images');
            $uploaded++;
        }

        return back()->with('success', "{$uploaded} image(s) uploaded successfully.");
    }

    public function index(Request $request)
    {
        $base = (new Image)->newQuery();

        if ($request->filled('search')) {
            $search = $request->search;
            $base->where(function ($q) use ($search) {
                $q->where('original_name', 'like', "%{$search}%")
                    ->orWhere('alt_text', 'like', "%{$search}%")
                    ->orWhere('title', 'like', "%{$search}%")
                    ->orWhere('filename', 'like', "%{$search}%");
            });
        }

        $convertibleMimes = ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif'];

        // Only show images whose actual file exists on disk, so the library
        // reflects real files rather than orphaned/soft-deleted records.
        $missingPaths = $this->missingImagePaths();
        $exists = function ($q) use ($missingPaths) {
            if (! empty($missingPaths)) {
                $q->whereNotIn('path', $missingPaths);
            }
        };
        $exists($base);

        // Since content consolidation, many rows share one file. Treat one
        // unique path as one image so counts and the grid show real images.
        $filter = $request->filter;
        if ($filter === 'unused') {
            $base->whereRaw('NOT EXISTS (SELECT 1 FROM images i2 WHERE i2.path = images.path AND i2.attachable_type IS NOT NULL AND i2.deleted_at IS NULL)');
        } elseif ($filter === 'attached') {
            $base->whereRaw('EXISTS (SELECT 1 FROM images i2 WHERE i2.path = images.path AND i2.attachable_type IS NOT NULL AND i2.deleted_at IS NULL)');
        } elseif ($filter === 'convertible') {
            $base->whereIn('mime_type', $convertibleMimes)
                ->whereRaw("SUBSTRING_INDEX(filename, '.', 1) NOT IN (SELECT SUBSTRING_INDEX(filename, '.', 1) FROM images WHERE mime_type = 'image/webp')");
        }

        $sort = $request->sort ?? 'created_at';
        $order = $request->order ?? 'desc';
        $agg = $sort === 'original_name' ? 'MAX(images.original_name)' : 'MAX(images.created_at)';
        $orderBy = $order === 'asc' ? 'asc' : 'desc';

        $paths = (clone $base)
            ->selectRaw('path, '.$agg.' AS _sort')
            ->groupBy('path')
            ->orderBy('_sort', $orderBy)
            ->paginate(80)->onEachSide(2)->withQueryString();

        $pathList = collect($paths->items())->pluck('path')->filter()->values();
        $representatives = $pathList->isEmpty()
            ? collect()
            : Image::whereIn('path', $pathList)->orderBy('created_at', 'desc')->get()->groupBy('path')->map->first();
        $paths->setCollection($pathList->map(fn ($p) => $representatives[$p] ?? null)->filter()->values());

        if ($request->ajax()) {
            return response()->json([
                'html' => view('admin.images._cards', ['images' => $paths])->render(),
                'current_page' => $paths->currentPage(),
                'last_page' => $paths->lastPage(),
                'total' => $paths->total(),
                'next_page_url' => $paths->nextPageUrl(),
            ]);
        }

        $statsQuery = (new Image)->newQuery()->tap($exists);
        $sizeQuery = (clone $statsQuery)->selectRaw('path, MAX(size) AS max_size')->groupBy('path')->get();
        $stats = [
            'total' => (clone $statsQuery)->distinct()->count('path'),
            'attached' => (clone $statsQuery)->whereNotNull('attachable_type')->distinct()->count('path'),
            'unused' => 0,
            'convertible' => (clone $statsQuery)->whereIn('mime_type', $convertibleMimes)
                ->whereRaw("SUBSTRING_INDEX(filename, '.', 1) NOT IN (SELECT SUBSTRING_INDEX(filename, '.', 1) FROM images WHERE mime_type = 'image/webp')")
                ->distinct()->count('path'),
            'total_size' => $sizeQuery->sum('max_size'),
        ];
        $stats['unused'] = max(0, $stats['total'] - $stats['attached']);

        return view('admin.images.index', [
            'images' => $paths,
            'stats' => $stats,
        ]);
    }

    /**
     * Paths of active image rows whose file is absent from disk.
     * Computed once per request to avoid repeated file_exists checks.
     *
     * @return array<int,string>
     */
    private function missingImagePaths(): array
    {
        $base = Storage::disk('public')->path('');
        $missing = [];
        foreach (Image::query()->pluck('path') as $path) {
            $path = (string) $path;
            $clean = ltrim(str_replace(['storage/', 'public/', '\\'], '', $path), '/');
            if (! $clean || str_starts_with($clean, 'http')) {
                continue;
            }
            if (! is_file($base.$clean)) {
                $missing[] = $path;
            }
        }

        return $missing;
    }

    public function edit($id)
    {
        $image = Image::with('attachable', 'products')->findOrFail($id);
        $usageLocations = $image->usageLocations();

        return view('admin.images.edit', compact('image', 'usageLocations'));
    }

    public function update(Request $request, $id)
    {
        $image = Image::findOrFail($id);

        $request->validate([
            'alt_text' => 'nullable|string|max:255',
            'title' => 'nullable|string|max:255',
            'caption' => 'nullable|string|max:500',
        ]);

        $image->update($request->only(['alt_text', 'title', 'caption']));

        return redirect()->route('admin.images.edit', $image->id)
            ->with('success', 'Image details updated successfully.');
    }

    public function convert($id)
    {
        $image = Image::findOrFail($id);

        if (! in_array($image->mime_type, ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif'])) {
            return back()->with('error', 'Only JPEG, PNG, and GIF images can be converted to WebP.');
        }

        $sourcePath = $image->file_path;
        if (! file_exists($sourcePath)) {
            return back()->with('error', 'File not found.');
        }

        $webpFilename = pathinfo($image->filename, PATHINFO_FILENAME).'.webp';

        if (Image::where('filename', $webpFilename)->exists()) {
            return back()->with('error', 'This image is already converted to WebP.');
        }

        $destPath = dirname($sourcePath).'/'.$webpFilename;

        if (! convertToWebp($sourcePath, $destPath, 80)) {
            return back()->with('error', 'Could not convert image to WebP.');
        }

        $webpSize = filesize($destPath);
        $webpInfo = getimagesize($destPath);

        $publicBase = public_path();
        $storageBase = storage_path('app/public');
        $relativePath = match (true) {
            str_starts_with($destPath, $publicBase) => substr($destPath, strlen($publicBase) + 1),
            str_starts_with($destPath, $storageBase) => substr($destPath, strlen($storageBase) + 1),
            default => pathinfo($image->path, PATHINFO_DIRNAME).'/'.$webpFilename,
        };
        $converted = Image::create([
            'original_name' => pathinfo($image->original_name, PATHINFO_FILENAME).'.webp',
            'filename' => $webpFilename,
            'path' => $relativePath,
            'url' => 'storage/'.$relativePath,
            'mime_type' => 'image/webp',
            'size' => $webpSize,
            'width' => $webpInfo[0] ?? null,
            'height' => $webpInfo[1] ?? null,
            'alt_text' => $image->alt_text,
            'title' => $image->title,
            'caption' => $image->caption,
            'attachable_type' => $image->attachable_type,
            'attachable_id' => $image->attachable_id,
        ]);

        return redirect()->route('admin.images.index')
            ->with('success', "Converted {$image->original_name} to {$converted->original_name} successfully.");
    }

    public function bulkConvert(Request $request)
    {
        $ids = $request->input('ids', []);
        if (empty($ids)) {
            return back()->with('error', 'No images selected.');
        }

        $images = Image::whereIn('id', $ids)
            ->whereIn('mime_type', ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'image/gif'])
            ->get();

        $converted = 0;
        $failed = 0;

        foreach ($images as $image) {
            try {
                $sourcePath = $image->file_path;
                if (! file_exists($sourcePath)) {
                    $failed++;

                    continue;
                }

                $webpFilename = pathinfo($image->filename, PATHINFO_FILENAME).'.webp';

                if (Image::where('filename', $webpFilename)->exists()) {
                    $converted++;

                    continue;
                }

                $destPath = dirname($sourcePath).'/'.$webpFilename;

                if (! convertToWebp($sourcePath, $destPath, 80)) {
                    $failed++;

                    continue;
                }

                $webpSize = filesize($destPath);
                $dimensions = getimagesize($destPath);

                $publicBase = public_path();
                $storageBase = storage_path('app/public');
                $relativePath = match (true) {
                    str_starts_with($destPath, $publicBase) => substr($destPath, strlen($publicBase) + 1),
                    str_starts_with($destPath, $storageBase) => substr($destPath, strlen($storageBase) + 1),
                    default => pathinfo($image->path, PATHINFO_DIRNAME).'/'.$webpFilename,
                };
                Image::create([
                    'original_name' => pathinfo($image->original_name, PATHINFO_FILENAME).'.webp',
                    'filename' => $webpFilename,
                    'path' => $relativePath,
                    'url' => 'storage/'.$relativePath,
                    'mime_type' => 'image/webp',
                    'size' => $webpSize,
                    'width' => $dimensions[0] ?? null,
                    'height' => $dimensions[1] ?? null,
                    'alt_text' => $image->alt_text,
                    'title' => $image->title,
                    'attachable_type' => $image->attachable_type,
                    'attachable_id' => $image->attachable_id,
                ]);

                $converted++;
            } catch (\Exception $e) {
                $failed++;
            }
        }

        return back()->with('success', "{$converted} images converted to WebP.".($failed ? " {$failed} failed." : ''));
    }

    public function bulkDelete(Request $request)
    {
        $ids = $request->input('ids', []);
        if (empty($ids)) {
            return back()->with('error', 'No images selected.');
        }

        $images = Image::whereIn('id', $ids)->get();

        $deleted = 0;
        $sharedSkipped = 0;
        foreach ($images as $image) {
            if (! empty($image->path)) {
                // After content consolidation many rows may share one file.
                // Only unlink when no other active (non-soft-deleted) row uses the same path.
                $shared = Image::where('path', $image->path)
                    ->where('id', '!=', $image->id)
                    ->exists();
            } else {
                $shared = false;
            }

            if ($shared) {
                $sharedSkipped++;
            } else {
                $filePath = $image->file_path;
                if (file_exists($filePath)) {
                    unlink($filePath);
                }
            }
            $image->delete();
            $deleted++;
        }

        return back()->with('success', "{$deleted} images deleted successfully.".($sharedSkipped ? " ({$sharedSkipped} shared files kept)." : ''));
    }

    public function bulkMarkUnused(Request $request)
    {
        $ids = $request->input('ids', []);
        if (empty($ids)) {
            return back()->with('error', 'No images selected.');
        }

        Image::whereIn('id', $ids)->update([
            'attachable_type' => null,
            'attachable_id' => null,
        ]);

        return back()->with('success', count($ids).' images marked as unused.');
    }
}
